require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
use_frameworks!

def shared_pods
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target 'KmSample' do
  shared_pods
  #pod 'RNKommunicateChat', :path => '../node_modules/react-native-kommunicate-chat'
  target 'KmSampleTests' do
    inherit! :complete
    # Pods for testing
  end
end

#$static_framework = ['react-native-slider', 'react-native-geolocation', 'RNImageToPdf', 'react-native-progress-view', 'RNFS', 'React-Core', 'React']
#pre_install do |installer|
#  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
#  installer.pod_targets.each do |pod|
#    if $static_framework.include?(pod.name)
#      def pod.build_type; Pod::BuildType.static_library
#    end
#  end
#end
#end
